services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/:ro
        ports:
            - "89:80"
        depends_on:
            - app
        container_name: ${APP_NAME}_nginx
        networks:
            - vacancies_network
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.catrina.one`)"
            - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
            - "traefik.http.routers.${APP_NAME}.tls.certresolver=myresolver"
            - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=80"
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        env_file:
            - .env
        volumes:
            - ./:/var/www/
        depends_on:
            - db
            - memcached
            - redis
        container_name: ${APP_NAME}
        dns:
            - 8.8.8.8
            - 8.8.4.4
        cap_add:
            - SYS_TIME  # Добавлено право для изменения системного времени
        networks:
            - vacancies_network
            - web

    memcached:
        image: memcached:latest
        container_name: ${APP_NAME}_memcached
        command: memcached -m 64 -p 11211 -u memcache -l 0.0.0.0 -U 0
        networks:
            - vacancies_network

    redis:
        image: redis:alpine
        container_name: ${APP_NAME}_redis
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data
        networks:
            - vacancies_network

    queue-worker:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        env_file:
            - .env
        volumes:
            - ./:/var/www/
        depends_on:
            - db
            - redis
        container_name: ${APP_NAME}_queue_worker
        command: php artisan queue:work --sleep=1 --tries=3 --max-time=3600
        dns:
            - 8.8.8.8
            - 8.8.4.4
        networks:
            - vacancies_network

    db:
        image: mysql
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
            - ./_docker/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=STRICT_TRANS_TABLES
        container_name: ${DB_HOST}
        networks:
            - vacancies_network

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "8089:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: ${DB_HOST}
        container_name: ${APP_NAME}_pma
        networks:
            - vacancies_network
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${APP_NAME}_phpmyadmin.rule=Host(`phpmyadmin.${APP_NAME}.catrina.one`)"
            - "traefik.http.routers.${APP_NAME}_phpmyadmin.entrypoints=websecure"
            - "traefik.http.routers.${APP_NAME}_phpmyadmin.tls.certresolver=myresolver"
            - "traefik.http.services.${APP_NAME}_phpmyadmin.loadbalancer.server.port=80"

volumes:
    redis_data:

networks:
    vacancies_network:
        driver: bridge
    web:
        external: true
